### ISSUE TITLE
Error running web app

### ISSUE THREAD

**Issue by ntourne** [nestor94/my-instagram#3]
Hi @nestor94,

I tried to run the web app but got this:

```
$ node index.js
Server Running on: 3030

/home/ntourne/projects/mobile/my-instagram/web/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
```

Maybe different mongodb version? I'm running mongodb v2.4.9.
Thanks.

**Comment by nescotos** [comment]
Hi, check if Mongo is listening that port.
I'm using Mongo 2.6.10
